### ISSUE TITLE
Batch requests?

### ISSUE THREAD

**Issue by dessalines** [vankasteelj/torrent-tracker-health#2]
I see that your `torrent-tracker` can do batch scrapes (lots of infohashes) , is there any way for this also to implement those?

**Comment by vankasteelj** [comment]
This should work: 

```js
var torrentHealth = require('torrent-tracker-health');
var magnetArray = [magnet1,magnet2];
Promise.all(magnetArray.map((magnet) => torrentHealth(magnet))).then(console.log)
```

**Comment by dessalines** [comment]
Would that still be doing separate requests though? I'm scraping thousands of torrents essentially and want to batch the tracker scrape requests, in the way that many trackers can receive requests for many infohashes.

**Comment by vankasteelj** [comment]
Ah ok. Well, I'll have to check that

**Comment by vankasteelj** [comment]
see #1
